# Generated by Django 4.2.16 on 2025-03-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_employee_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarskip',
            name='date_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendarvacation',
            name='date_since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
