# Generated by Django 4.2.16 on 2025-03-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_event_description_alter_event_education_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
